title: National Elections Database
remote_theme: aterenin/minima-reboot # base theme to be loaded
baseurl: "" # Empty as site is in base folder
url: https://nationalelectionsdatabase.com # GitHub Pages URL

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
#- home.md
- data-downloads.md

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
  - README.md

  

